definitions["0,0,0"] = function() {
  print("Hello!<br><br>You are viewing a short example game. Replace the 'definitions.js' file with one generated by the Icycle Editor (choose the 'Export Gamescript' option in the 'Publish Game' menu) to inject your game into the Runtime Engine!");
  roomName("Message");
}
